# Script to remove safe to remove apps from my phone.
# This has been tested, and works immediately after factory reset.

pm uninstall --user 0 android.autoinstalls.config.samsung                                   
pm uninstall --user 0 com.monotype.android.font.samsungone                                  
pm uninstall --user 0 com.samsung.SMT                                                       
pm uninstall --user 0 com.samsung.aasaservice                                               
pm uninstall --user 0 com.samsung.android.aircommandmanager                                 
pm uninstall --user 0 com.samsung.android.allshare.service.mediashare                       
pm uninstall --user 0 com.samsung.android.app.appsedge                                      
pm uninstall --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload           
pm uninstall --user 0 com.samsung.android.app.clipboardedge                                 
pm uninstall --user 0 com.samsung.android.app.cocktailbarservice                            
pm uninstall --user 0 com.samsung.android.app.dressroom                                     
pm uninstall --user 0 com.samsung.android.app.ledbackcover                                  
pm uninstall --user 0 com.samsung.android.app.omcagent                                      
pm uninstall --user 0 com.samsung.android.app.reminder                                      
pm uninstall --user 0 com.samsung.android.app.routines                                      
pm uninstall --user 0 com.samsung.android.app.settings.bixby                                
pm uninstall --user 0 com.samsung.android.app.simplesharing                                 
pm uninstall --user 0 com.samsung.android.app.spage                                         
pm uninstall --user 0 com.samsung.android.app.taskedge                                      
pm uninstall --user 0 com.samsung.android.app.tips                                          
pm uninstall --user 0 com.samsung.android.app.watchmanagerstub                              
pm uninstall --user 0 com.samsung.android.ardrawing                                         
pm uninstall --user 0 com.samsung.android.aremoji                                           
pm uninstall --user 0 com.samsung.android.aremojieditor                                     
pm uninstall --user 0 com.samsung.android.arzone                                            
pm uninstall --user 0 com.samsung.android.authfw                                            
pm uninstall --user 0 com.samsung.android.aware.service                                     
pm uninstall --user 0 com.samsung.android.beaconmanager                                     
pm uninstall --user 0 com.samsung.android.bixby.service                                     
pm uninstall --user 0 com.samsung.android.calendar                                          
pm uninstall --user 0 com.samsung.android.da.daagent                                        
pm uninstall --user 0 com.samsung.android.dqagent                                           
pm uninstall --user 0 com.samsung.android.dynamiclock                                       
pm uninstall --user 0 com.samsung.android.easysetup                                         
pm uninstall --user 0 com.samsung.android.fmm                                               
pm uninstall --user 0 com.samsung.android.forest                                            
pm uninstall --user 0 com.samsung.android.game.gamehome                                     
pm uninstall --user 0 com.samsung.android.game.gametools                                    
pm uninstall --user 0 com.samsung.android.game.gos                                          
pm uninstall --user 0 com.samsung.android.icecone                                           
pm uninstall --user 0 com.samsung.android.ipsgeofence                                       
pm uninstall --user 0 com.samsung.android.kidsinstaller                                     
pm uninstall --user 0 com.samsung.android.knox.analytics.uploader                           
pm uninstall --user 0 com.samsung.android.knox.attestation                                  
pm uninstall --user 0 com.samsung.android.knox.containercore                                
pm uninstall --user 0 com.samsung.android.livestickers                                      
pm uninstall --user 0 com.samsung.android.location                                          
pm uninstall --user 0 com.samsung.android.mateagent                                         
pm uninstall --user 0 com.samsung.android.mdm                                               
pm uninstall --user 0 com.samsung.android.mdx                                               
pm uninstall --user 0 com.samsung.android.mdx.kit                                           
pm uninstall --user 0 com.samsung.android.mdx.quickboard                                    
pm uninstall --user 0 com.samsung.android.mobileservice                                     
pm uninstall --user 0 com.samsung.android.net.wifi.wifiguider                               
pm uninstall --user 0 com.samsung.android.networkdiagnostic                                 
pm uninstall --user 0 com.samsung.android.rubin.app                                         
pm uninstall --user 0 com.samsung.android.samsungpass                                       
pm uninstall --user 0 com.samsung.android.samsungpassautofill                               
pm uninstall --user 0 com.samsung.android.samsungpositioning                                
pm uninstall --user 0 com.samsung.android.securitylogagent                                  
pm uninstall --user 0 com.samsung.android.service.livedrawing                               
pm uninstall --user 0 com.samsung.android.service.peoplestripe                              
pm uninstall --user 0 com.samsung.android.shortcutbackupservice                             
pm uninstall --user 0 com.samsung.android.smartcallprovider                                 
pm uninstall --user 0 com.samsung.android.smartface                                         
pm uninstall --user 0 com.samsung.android.smartmirroring                                    
pm uninstall --user 0 com.samsung.android.spay                                              
pm uninstall --user 0 com.samsung.android.stickercenter                                     
pm uninstall --user 0 com.samsung.android.svcagent                                          
pm uninstall --user 0 com.samsung.android.svoiceime                                         
pm uninstall --user 0 com.samsung.android.themecenter                                       
pm uninstall --user 0 com.samsung.android.themestore                                        
pm uninstall --user 0 com.samsung.android.visionintelligence                                
pm uninstall --user 0 com.samsung.app.highlightplayer                                       
pm uninstall --user 0 com.samsung.desktopsystemui                                           
pm uninstall --user 0 com.samsung.klmsagent                                                 
pm uninstall --user 0 com.samsung.knox.keychain                                             
pm uninstall --user 0 com.samsung.mlp                                                       
pm uninstall --user 0 com.samsung.safetyinformation                                         
pm uninstall --user 0 com.samsung.storyservice                                              
pm uninstall --user 0 com.samsung.systemui.bixby2                                           
pm uninstall --user 0 com.samsung.ucs.agent.ese                                             
pm uninstall --user 0 com.samsung.vvm                                                       
pm uninstall --user 0 com.sec.android.RilServiceModeApp                                     
pm uninstall --user 0 com.sec.android.app.DataCreate                                        
pm uninstall --user 0 com.sec.android.app.SecSetupWizard                                    
pm uninstall --user 0 com.sec.android.app.apex                                              
pm uninstall --user 0 com.sec.android.app.applinker                                         
pm uninstall --user 0 com.sec.android.app.billing                                           
pm uninstall --user 0 com.sec.android.app.bluetoothtest                                     
pm uninstall --user 0 com.sec.android.app.camera                                            
pm uninstall --user 0 com.sec.android.app.chromecustomizations                              
pm uninstall --user 0 com.sec.android.app.desktoplauncher                                   
pm uninstall --user 0 com.sec.android.app.dexonpc                                           
pm uninstall --user 0 com.sec.android.app.factorykeystring                                  
pm uninstall --user 0 com.sec.android.app.magnifier                                         
pm uninstall --user 0 com.sec.android.app.myfiles                                           
pm uninstall --user 0 com.sec.android.app.quicktool                                         
pm uninstall --user 0 com.sec.android.app.safetyassurance                                   
pm uninstall --user 0 com.sec.android.app.samsungapps                                       
pm uninstall --user 0 com.sec.android.app.sbrowser                                          
pm uninstall --user 0 com.sec.android.app.setupwizard                                       
pm uninstall --user 0 com.sec.android.app.wlantest                                          
pm uninstall --user 0 com.sec.android.cover.ledcover                                        
pm uninstall --user 0 com.sec.android.daemonapp                                             
pm uninstall --user 0 com.sec.android.desktopmode.uiservice                                 
pm uninstall --user 0 com.sec.android.easyMover                                             
pm uninstall --user 0 com.sec.android.easyMover.Agent                                       
pm uninstall --user 0 com.sec.android.easyonehand                                           
pm uninstall --user 0 com.sec.android.mimage.avatarstickers                                 
pm uninstall --user 0 com.sec.android.preloadinstaller                                      
pm uninstall --user 0 com.sec.app.RilErrorNotifier                                          
pm uninstall --user 0 com.sec.bcservice                                                     
pm uninstall --user 0 com.sec.enterprise.knox.attestation                                   
pm uninstall --user 0 com.sec.enterprise.knox.cloudmdm.smdms                                
pm uninstall --user 0 com.sec.enterprise.mdm.services.simpin                                
pm uninstall --user 0 com.sec.epdgtestapp                                                   
pm uninstall --user 0 com.sec.factory                                                       
pm uninstall --user 0 com.sec.hiddenmenu                                                    
pm uninstall --user 0 com.sec.imslogger                                                     
pm uninstall --user 0 com.sec.location.nsflp2                                               
pm uninstall --user 0 com.sec.modem.settings                                                
pm uninstall --user 0 com.sec.phone                                                         
pm uninstall --user 0 com.sec.spp.push                                                      
pm uninstall --user 0 com.sec.sve                                                           
pm uninstall --user 0 com.sec.usbsettings                                                   
pm uninstall --user 0 com.skms.android.agent                                                
pm uninstall --user 0 com.wsomacp                                                           
